# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper-svmodt.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 5)
knitr::opts_knit$set(latex_engine = "xelatex")
library(kableExtra)
library(dplyr)
#devtools::install_github("AneeshAgarwala/svmodt")
library(svmodt)
library(palmerpenguins)
library(rpart)
library(kernlab)
library(rsample)
library(ggplot2)
library(patchwork)
library(purrr)
library(aorsf)
library(tidyr)
library(gridExtra)


## ----palmer-penguins-introduction-split, fig.align='center', results='asis', fig.cap="Comparison of Axis-parallel and Axis-oblique splits on Palmerpenguins dataset.", fig.subcap=c('axis-parallel split', 'axis-oblique split'), out.width = '50%', cache=TRUE----
penguins_orsf <- penguins |> drop_na()

penguins_orsf$flipper_length_mm <- as.numeric(penguins_orsf$flipper_length_mm)

plot_decision_surface <- function(predictions, 
                                  #title, 
                                  grid){
 class_preds <- bind_cols(grid, predictions) %>%
  pivot_longer(cols = c(Adelie,
                        Chinstrap,
                        Gentoo)) %>%
  group_by(flipper_length_mm, bill_length_mm) %>%
  arrange(desc(value)) %>%
  slice(1)
 
 cols <- c("darkorange", "purple", "cyan4")

 ggplot(class_preds, aes(bill_length_mm, flipper_length_mm)) +
  geom_tile(aes(fill = name), alpha = 0.25) +
  #geom_contour_filled(aes(z = value, fill = name),
  #                    alpha = .25) +
  geom_point(data = penguins_orsf,
             aes(color = species, shape = species),
             alpha = 0.5) +
  scale_color_manual(values = cols) +
  scale_fill_manual(values = cols) +
  labs(x = "Bill length, mm",
       y = "Flipper length, mm") +
  theme_minimal() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(fill = NA),
        legend.position = '',
        aspect.ratio = 1,
        # plot.title = element_text(size = 10, hjust = 0.5)
        )#+
  #labs(title = title)
 
}


grid <- expand_grid(
 flipper_length_mm = seq(min(penguins_orsf$flipper_length_mm),
                     max(penguins_orsf$flipper_length_mm),
                  len = 200),
 bill_length_mm = seq(min(penguins_orsf$bill_length_mm),
                      max(penguins_orsf$bill_length_mm),
                      len = 200)
)

fit_axis_tree <- penguins_orsf %>% 
 orsf(species ~ flipper_length_mm + bill_length_mm,
      n_tree = 1,
      mtry = 1,
      tree_seeds = 106760)

#fit_axis_forest <- fit_axis_tree %>% 
# orsf_update(n_tree = 500)

fit_oblique_tree <- fit_axis_tree %>% 
 orsf_update(mtry = 2)

#fit_oblique_forest <- fit_oblique_tree %>% 
# orsf_update(n_tree = 500)

preds <- list(fit_axis_tree,
              fit_oblique_tree) |> 
 map(predict, new_data = grid, pred_type = 'prob')

titles <- c("AXIS-PARALLEL SPLIT",
#            "Axis-based forest",
            "AXIS-OBLIQUE SPLIT"
#            "Oblique forest"
)

plots <- map(preds, plot_decision_surface, grid = grid)

plots[[1]]
plots[[2]]


## ----table-benchmark-streer---------------------------------------------------
r_stree <- readRDS("analysis/results/r_stree.rds")
py_stree <- readRDS("analysis/results/py_stree.rds")
time_bench <- readRDS("analysis/results/time-benchmark.rds")
#readRDS("analysis/results/optimised_r_stree.rds")

data_names <- c("WDBC Diagnosis", "Iris", "Echocardiogram", "Fertility", "Wine", "Cardiotography-3", "Cardiotography-10", "Ionosphere", "Dermatology", "Statlog Australian Credit")
data_num_observations <- c(569, 150, 131, 100, 178, 2126, 2126, 351, 366, 690)
data_num_features <- c(30, 4, 10, 9, 12, 21, 21, 33, 34, 14) 
data_num_classes <- c(2, 3, 2, 2, 3, 3, 10, 2, 6, 2)

mean_sd <- function(x, digits = 3) {
  x <- as.numeric(x)
  m <- mean(x, na.rm = TRUE)
  s <- sd(x, na.rm = TRUE)
  sprintf(paste0("%.", digits, "f \u00B1 %.", digits, "f"), m, s)
}

time_suffix <- function(x, digits = 3){
  x = as.numeric(x)
  paste0(round(x, digits),"ms")
}

tbl <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  apply(as.matrix(r_stree), 2, mean_sd),
  apply(as.matrix(py_stree), 2, mean_sd),
  apply(time_bench, 2, time_suffix),
  stringsAsFactors = FALSE
)


tbl_bold <- tbl
model_cols <- 5:6

tbl_bold[model_cols] <- t(apply(tbl[model_cols], 1, function(row) {
  
  # extract means from "mean ± sd"
  means <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))

tbl_bold |>
  kable(
    row.names = FALSE,
    col.names = c("Dataset", "N", "X", "L", "StreeR", "STree", "StreeR(Med)", "Stree(Med)"),
    align = "lccccccc",
    escape = FALSE, 
    caption = "Comparison of Mean Prediction Accuracy and Median Training Time for STreeR and STree"
  ) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8
  ) 


## ----eval=FALSE, echo=FALSE---------------------------------------------------
# svmodt::svm_split(data = ,depth = ,max_depth = ,min_samples = , feature_method = , max_features = , max_features_strategy = , penalize_used_features = )


## ----stree-svmodt-benchmark-table, cache=TRUE, echo=FALSE, eval=FALSE---------
# # source(file = "analysis/5-fold-cv-benchmark.R", local = TRUE)
# #
# # # Default R Stree
# # r_stree_results <- cbind(stat_wdbc, stat_iris, stat_echocardiogram, stat_fertility, stat_wine, stat_ctg3, stat_ctg10, stat_ionosphere, stat_dermatology, stat_aus_credit)
# #
# # r_stree_results |> saveRDS(file = "analysis/results/r_stree.rds")
# #
# #
# # # Default R Svmodt
# # r_svmodt_results <- cbind(stat_svmodt_wdbc, stat_svmodt_iris, stat_svmodt_echocardiogram, stat_svmodt_fertility, stat_svmodt_wine, stat_svmodt_ctg3, stat_svmodt_ctg10, stat_svmodt_ionosphere, stat_svmodt_dermatology, stat_svmodt_aus_credit)
# #
# # r_svmodt_results |> saveRDS(file = "analysis/results/r_svmodt.rds")
# #
# # # Optimised R Stree
# # opt_stree_results <- cbind(opt_stat_wdbc, opt_stat_iris, opt_stat_echocardiogram, opt_stat_fertility, opt_stat_wine, opt_stat_ctg3, opt_stat_ctg10, opt_stat_ionosphere, opt_stat_dermatology, opt_stat_aus_credit)
# #
# # opt_stree_results |> saveRDS(file = "analysis/results/optimised_r_stree.rds")
# #
# # # Default Python Stree
# # py_stree_results <- cbind(py_stree_wdbc, py_stree_iris, py_stree_echocardiogram, py_stree_fertility, py_stree_wine, py_stree_ctg3, py_stree_ctg10, py_stree_ionosphere, py_stree_dermatology, py_stree_aus_credit)
# # #
# # py_stree_results |> saveRDS(file = "analysis/results/py_stree.rds")
# 
# r_svmodt <- readRDS("analysis/results/r_svmodt.rds")
# r_stree <- readRDS("analysis/results/r_stree.rds")
# py_stree <- readRDS("analysis/results/py_stree.rds")
# #readRDS("analysis/results/optimised_r_stree.rds")
# 
# data_names <- c("WDBC Diagnosis", "Iris", "Echocardiogram", "Fertility", "Wine", "Cardiotography-3", "Cardiotography-10", "Ionosphere", "Dermatology", "Statlog Australian Credit")
# 
# mean_sd <- function(x, digits = 3) {
#   x <- as.numeric(x)
#   m <- mean(x, na.rm = TRUE)
#   s <- sd(x, na.rm = TRUE)
#   sprintf(paste0("%.", digits, "f \u00B1 %.", digits, "f"), m, s)
# }
# 
# tbl <- data.frame(
#   data_names,
#   apply(as.matrix(r_stree), 2, mean_sd),
#   apply(as.matrix(py_stree), 2, mean_sd),
#   apply(as.matrix(r_svmodt), 2, mean_sd),
#   stringsAsFactors = FALSE
# )
# 
# 
# tbl_bold <- tbl
# model_cols <- 2:ncol(tbl_bold)
# 
# tbl_bold[model_cols] <- t(apply(tbl[model_cols], 1, function(row) {
# 
#   # extract means from "mean ± sd"
#   means <- as.numeric(sub(" \u00B1.*", "", row))
#   max_idx <- which(means == max(means, na.rm = TRUE))
# 
#   out <- row
#   out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
#   out
# }))
# 
# tbl_bold |>
#   kable(
#     row.names = FALSE,
#     col.names = c("Dataset", "Stree(R)", "STree(Python)", "SVMODT"),
#     align = "lccc",
#     escape = FALSE,
#     caption = "Comparing Mean Prediction Accuracy with default arguments - STree(R), STree(Python), SVMODT"
#   ) |>
#   kable_styling(
#     full_width = FALSE,
#     position = "center"
#   )

