# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper-svmodt.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 5)
knitr::opts_knit$set(latex_engine = "xelatex")
library(kableExtra)
library(dplyr)
# devtools::install_github("AneeshAgarwala/svmodt")
#install.packages("../project-svodt/", repos = NULL, type = "source")
library(svmodt)
library(palmerpenguins)
library(rpart)
library(kernlab)
library(rsample)
library(ggplot2)
library(patchwork)
library(purrr)
library(aorsf)
library(tidyr)
library(gridExtra)
library(ggpubr)


## ----palmer-penguins-introduction-split, fig.align='center', results='asis', fig.cap="Comparison of axis-parallel and axis-oblique decision boundaries on the Palmerpenguins dataset using bill length (mm) and flipper length (mm) as predictor variables.", fig.subcap=c('axis-parallel split', 'axis-oblique split'), out.width = '80%', cache=TRUE----
penguins_orsf <- penguins |> drop_na()

penguins_orsf$flipper_length_mm <- as.numeric(penguins_orsf$flipper_length_mm)

penguins_orsf <- penguins_orsf |> svmodt:::standard_scaler()

plot_decision_surface <- function(predictions,
                                  # title,
                                  grid) {
  class_preds <- bind_cols(grid, predictions) %>%
    pivot_longer(cols = c(
      Adelie,
      Chinstrap,
      Gentoo
    )) %>%
    group_by(flipper_length_mm, bill_length_mm) %>%
    arrange(desc(value)) %>%
    slice(1)

  cols <- c("darkorange", "purple", "cyan4")

  ggplot(class_preds, aes(bill_length_mm, flipper_length_mm)) +
    geom_tile(aes(fill = name), alpha = 0.25) +
    # geom_contour_filled(aes(z = value, fill = name),
    #                    alpha = .25) +
    geom_point(
      data = penguins_orsf,
      aes(color = species, shape = species),
      size = 1,
      alpha = 0.5
    ) +
    scale_color_manual(values = cols) +
    scale_fill_manual(values = cols, guide = "none") +
    labs(
      x = "Bill length, mm",
      y = "Flipper length, mm"
    ) +
    theme_minimal() +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    theme(
      panel.grid = element_blank(),
      panel.border = element_rect(fill = NA),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 6),
      axis.title.x = element_text(size = 8),
      axis.title.y = element_text(size = 8),
      aspect.ratio = 1,
    )
}


grid <- expand_grid(
  flipper_length_mm = seq(min(penguins_orsf$flipper_length_mm),
    max(penguins_orsf$flipper_length_mm),
    len = 200
  ),
  bill_length_mm = seq(min(penguins_orsf$bill_length_mm),
    max(penguins_orsf$bill_length_mm),
    len = 200
  )
)

fit_axis_tree <- penguins_orsf %>%
  orsf(species ~ flipper_length_mm + bill_length_mm,
    n_tree = 1,
    mtry = 1,
    tree_seeds = 106760
  )

# fit_axis_forest <- fit_axis_tree %>%
# orsf_update(n_tree = 500)

fit_oblique_tree <- fit_axis_tree %>%
  orsf_update(mtry = 2)

# fit_oblique_forest <- fit_oblique_tree %>%
# orsf_update(n_tree = 500)

preds <- list(
  fit_axis_tree,
  fit_oblique_tree
) |>
  map(predict, new_data = grid, pred_type = "prob")

titles <- c(
  "AXIS-PARALLEL SPLIT",
  #            "Axis-based forest",
  "AXIS-OBLIQUE SPLIT"
  #            "Oblique forest"
)

plots <- map(preds, plot_decision_surface, grid = grid)


ggarrange(plots[[1]], plots[[2]], ncol = 2, common.legend = TRUE, legend = "right")


## ----table-benchmark-streer-latex, eval= knitr::is_latex_output()-------------
r_stree <- readRDS("analysis/results/r_stree.rds")
py_stree <- readRDS("analysis/results/py_stree.rds")
time_bench <- readRDS("analysis/results/time-benchmark.rds")

r_stree <- r_stree[,1:9]
py_stree <- py_stree[,1:9]
time_bench <- time_bench[1:9,]


time_bench <- time_bench[, -2]
# readRDS("analysis/results/optimised_r_stree.rds")

data_names <- c("WDBC Diagnosis", "Iris", "Echocardiogram", "Fertility", "Wine", "Cardiotocography-3", "Cardiotocography-10", "Ionosphere", "Dermatology")
data_num_observations <- c(569, 150, 131, 100, 178, 2126, 2126, 351, 366)
data_num_features <- c(30, 4, 10, 9, 13, 21, 21, 33, 34)
data_num_classes <- c(2, 3, 2, 2, 3, 3, 10, 2, 6)

mean_sd <- function(x, digits = 3) {
  x <- as.numeric(x)
  m <- mean(x, na.rm = TRUE)
  s <- sd(x, na.rm = TRUE)
  sprintf(paste0("%.", digits, "f \u00B1 %.", digits, "f"), m, s)
}

time_suffix <- function(x, digits = 3) {
  x <- as.numeric(x)
  paste0(round(x, digits), "ms")
}

tbl <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  apply(as.matrix(r_stree), 2, mean_sd),
  apply(as.matrix(py_stree), 2, mean_sd),
  apply(time_bench, 2, time_suffix),
  stringsAsFactors = FALSE
)


tbl_bold <- tbl
model_cols <- 5:6

tbl_bold[model_cols] <- t(apply(tbl[model_cols], 1, function(row) {
  # extract means from "mean ± sd"
  means <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))

  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))

tbl_bold |>
  kable(
    row.names = FALSE,
    col.names = c("Dataset", "N", "X", "L", "STreeR", "STree", "STreeR(Med)", "Stree(Med)"),
    align = "lccccccc",
    escape = FALSE,
    caption = "Comparison of mean prediction accuracy and median training time for STreeR and STree. Here, \\(N\\) denotes the number of observations, \\(X\\) the number of features, and \\(L\\) the number of classes."
  ) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8
  )


## ----table-benchmark-streer-html, eval= knitr::is_html_output()---------------
# r_stree <- readRDS("analysis/results/r_stree.rds")
# py_stree <- readRDS("analysis/results/py_stree.rds")
# time_bench <- readRDS("analysis/results/time-benchmark.rds")
# 
# r_stree <- r_stree[, 1:9]
# py_stree <- py_stree[, 1:9]
# time_bench <- time_bench[1:9, ]
# 
# time_bench <- time_bench[, -2]
# 
# data_names <- c("WDBC Diagnosis", "Iris", "Echocardiogram", "Fertility", "Wine", "Cardiotocography-3", "Cardiotocography-10", "Ionosphere", "Dermatology")
# data_num_observations <- c(569, 150, 131, 100, 178, 2126, 2126, 351, 366)
# data_num_features <- c(30, 4, 10, 9, 13, 21, 21, 33, 34)
# data_num_classes <- c(2, 3, 2, 2, 3, 3, 10, 2, 6)
# 
# mean_sd <- function(x, digits = 3) {
#   x <- as.numeric(x)
#   m <- mean(x, na.rm = TRUE)
#   s <- sd(x, na.rm = TRUE)
#   sprintf(paste0("%.", digits, "f \u00B1 %.", digits, "f"), m, s)
# }
# 
# time_suffix <- function(x, digits = 3) {
#   x <- as.numeric(x)
#   paste0(round(x, digits), " ms")
# }
# 
# tbl <- data.frame(
#   data_names,
#   data_num_observations,
#   data_num_features,
#   data_num_classes,
#   apply(as.matrix(r_stree), 2, mean_sd),
#   apply(as.matrix(py_stree), 2, mean_sd),
#   apply(time_bench, 2, time_suffix),
#   stringsAsFactors = FALSE
# )
# 
# tbl_bold <- tbl
# model_cols <- 5:6
# 
# tbl_bold[model_cols] <- t(apply(tbl[model_cols], 1, function(row) {
#   means <- as.numeric(sub(" \u00B1.*", "", row))
#   max_idx <- which(means == max(means, na.rm = TRUE))
#   out <- row
#   out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
#   out
# }))
# 
# kbl(tbl_bold,
#     col.names = c("Dataset", "N", "X", "L", "STreeR", "STree", "STreeR (Med)", "Stree (Med)"),
#     align = "lccccccc",
#     escape = FALSE,
#     caption = "Comparison of mean prediction accuracy and median training time for STreeR and STree. Here, \\(N\\) denotes the number of observations, \\(X\\) the number of features, and \\(L\\) the number of classes."
# ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## -----------------------------------------------------------------------------
source(file = "analysis/plot-surface.R")


## ----palmer-penguins-max-feature-selection-latex, eval=knitr::is_latex_output(), fig.align='center', results='asis', fig.cap="Comparison of constant, decreasing, and random maximum feature selection strategies using SVMODT on the Palmer Penguins dataset.", fig.subcap=c('constant', 'decrease', 'random'), fig.width = 6----
penguins_orsf <- penguins |>
  select(-island, -sex, -year) |>
  drop_na() |>
  svmodt:::standard_scaler()
  
penguins_orsf$flipper_length_mm <- as.numeric(penguins_orsf$flipper_length_mm)

fit_constant <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features_strategy = "constant"
)

fit_decrease <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features_strategy = "decrease",
  max_features_decrease_rate = 0.5
)

set.seed(235)
fit_random <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features_strategy = "random",
  max_features_random_range = c(0.5, 0.8)
)

plot1 <- plot_svmodt_surface(fit_constant, penguins_orsf, "species")
plot2 <- plot_svmodt_surface(fit_decrease, penguins_orsf, "species")
plot3 <- plot_svmodt_surface(fit_random, penguins_orsf, "species")

ggarrange(plot1, plot2, plot3, nrow = 1, common.legend = TRUE, legend = "right")


## ----palmer-penguins-max-feature-selection-html, eval=knitr::is_html_output(), fig.align='center', results='asis', fig.cap="Comparison of constant, decreasing, and random maximum feature selection strategies using SVMODT on the Palmer Penguins dataset.", fig.subcap=c('constant', 'decrease', 'random'), out.width = '30%'----
# knitr::include_graphics(path = "analysis/results/max-feature-selection/constant/tour-constant.gif")
# knitr::include_graphics(path = "analysis/results/max-feature-selection/decrease/tour-decrease.gif")
# knitr::include_graphics(path = "analysis/results/max-feature-selection/random/tour-random.gif")


## ----svmodt-max-features-accuracy-score-table---------------------------------
# Load results
svmodt_max_features_constant <- readRDS("analysis/results/svmodt_mf_constant.rds")
svmodt_max_features_decrease <- readRDS("analysis/results/svmodt_mf_decrease.rds")
svmodt_max_features_random <- readRDS("analysis/results/svmodt_mf_random.rds")
py_stree <- readRDS("analysis/results/py_stree.rds")


svmodt_max_features_random <- svmodt_max_features_random[,1:9]
svmodt_max_features_constant <- svmodt_max_features_constant[,1:9]
svmodt_max_features_decrease <- svmodt_max_features_decrease[,1:9]
py_stree <- py_stree[,1:9]


tbl_max_features <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  apply(as.matrix(py_stree), 2, mean_sd), # accuracy (benchmark)
  apply(as.matrix(svmodt_max_features_constant), 2, mean_sd),
  apply(as.matrix(svmodt_max_features_decrease), 2, mean_sd),
  apply(as.matrix(svmodt_max_features_random), 2, mean_sd),
  stringsAsFactors = FALSE
)

model_cols_f1 <- 5:8

tbl_max_features_bold <- tbl_max_features
tbl_max_features_bold[model_cols_f1] <- t(apply(tbl_max_features[model_cols_f1], 1, function(row) {
  means <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))


## ----svmodt-max-features-accuracy-score-table-latex, eval=knitr::is_latex_output()----
tbl_max_features_bold |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L",
      "STree", "Constant", "Decrease", "Random"
    ),
    align = "lccccccc",
    escape = FALSE,
    caption = paste0(
  "Comparison of mean prediction accuracy (mean \\(\\pm\\) standard deviation) across maximum feature selection strategies for SVMODT, with results benchmarked against the Python STree implementation All SVMODT models were trained using maximum depth parameter (\\(d_{\\max}=15\\)), mutual-information feature ranking, and adaptive feature selection. The constant strategy uses a fixed number of candidate features at each node; the decrease strategy progressively reduces the number of available features with tree depth (\\(\\alpha\\) = 0.5); the random strategy samples the candidate feature proportion uniformly from the interval \\(l_{\\min}=0.5\\) to \\(l_{\\max}=0.8\\) at each split. Bold values indicate the highest prediction accuracy for each dataset."
    )
  ) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 8
  )


## ----svmodt-max-features-accuracy-score-table-html, eval=knitr::is_html_output()----
# tbl_max_features_bold |>
#   kbl(
#     row.names = FALSE,
#     col.names = c(
#       "Dataset", "N", "X", "L",
#       "STree", "Constant", "Decrease", "Random"
#     ),
#     align = "lccccccc",
#     escape = FALSE,
#     caption = paste0(
#       "Comparison of mean prediction accuracy (mean \\(\\pm\\) standard deviation) across maximum feature selection strategies for SVMODT, with results benchmarked against the Python STree implementation All SVMODT models were trained using maximum depth parameter (\\(d_{\\max}=15\\)), mutual-information feature ranking, and adaptive feature selection. The constant strategy uses a fixed number of candidate features at each node; the decrease strategy progressively reduces the number of available features with tree depth (\\(\\alpha\\) = 0.5); the random strategy samples the candidate feature proportion uniformly from the interval \\(l_{\\min}=0.5\\) to \\(l_{\\max}=0.8\\) at each split. Bold values indicate the highest prediction accuracy for each dataset."
# )
#   ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----palmer-penguins-feature-selection-split-latex, eval = knitr::is_latex_output(), fig.align='center', results='asis', fig.cap="Comparison of random, mutual, and correlated feature selection methods using SVMODT on the Palmer Penguins dataset.", fig.subcap=c('random', 'mutual', 'correlation'), fig.width = 6----
# penguins_orsf$island <- as.numeric(penguins_orsf$island)
# penguins_orsf$sex <- as.numeric(penguins_orsf$sex)

# Train different SVMODT models
set.seed(235)
fit_random <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "random", n_subsets = 10,
  max_features = 3
)

fit_mutual <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  max_features = 3,
  feature_method = "mutual"
)

fit_cor <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 3,
  min_samples = 5,
  max_features = 3,
  feature_method = "cor"
)


# Create plots
plot1 <- plot_svmodt_surface(fit_random, penguins_orsf, "species")
plot2 <- plot_svmodt_surface(fit_mutual, penguins_orsf, "species")
plot3 <- plot_svmodt_surface(fit_cor, penguins_orsf, "species")

# Display plots
ggarrange(plot1, plot2, plot3, nrow = 1, common.legend = TRUE, legend = "right")


## ----palmer-penguins-feature-selection-split-html, eval = knitr::is_html_output(), fig.align='center', results='asis', fig.cap="Comparison of random, mutual, and correlated feature selection methods using SVMODT on the Palmer Penguins dataset.", fig.subcap=c('random', 'mutual', 'correlation'), out.width = '30%'----
# knitr::include_graphics(path = "analysis/results/feature-selection/random/tour-random.gif")
# knitr::include_graphics(path = "analysis/results/feature-selection/mutual/tour-mutual.gif")
# knitr::include_graphics(path = "analysis/results/feature-selection/corr/tour-corr.gif")


## ----svmodt-feature-selection-table-setup-------------------------------------
# Load results
svmodt_random <- readRDS("analysis/results/svmodt_feature_random.rds")
svmodt_mutual <- readRDS("analysis/results/svmodt_feature_mutual.rds")
svmodt_cor <- readRDS("analysis/results/svmodt_feature_cor.rds")
py_stree <- readRDS("analysis/results/py_stree.rds")


svmodt_random <- svmodt_random[,1:9]
svmodt_mutual <- svmodt_mutual[,1:9]
svmodt_cor <- svmodt_cor[,1:9]
py_stree <- py_stree[,1:9]

# ── Table 1: Feature Selection ────────────────────────────────────────────────
tbl_feature <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  apply(as.matrix(py_stree), 2, mean_sd),
  apply(as.matrix(svmodt_random), 2, mean_sd),
  apply(as.matrix(svmodt_mutual), 2, mean_sd),
  apply(as.matrix(svmodt_cor), 2, mean_sd),
  stringsAsFactors = FALSE
)

model_cols_feature <- 5:8

tbl_feature_bold <- tbl_feature
tbl_feature_bold[model_cols_feature] <- t(apply(tbl_feature[model_cols_feature], 1, function(row) {
  means <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))


## ----svmodt-feature-selection-table-latex, eval=knitr::is_latex_output()------
tbl_feature_bold |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L",
      "STree (Benchmark)", "Random", "Mutual Info", "Correlation"
    ),
    align = "lcccccccc",
    escape = FALSE,
    caption = paste0(
  "Comparison of mean prediction accuracy across feature selection strategies for SVMODT, benchmarked against the Python STree implementation. All SVMODT models were trained using \\(d_{\\max}=15\\). The random strategy selects candidate predictors using random subset sampling \\(n_{\\text{subsets}} = 10\\); the mutual information strategy ranks predictors according to their dependency with the response variable; the correlation strategy ranks predictors using absolute correlation with the response. STree does not employ an explicit pre-split feature ranking mechanism, instead optimising the node classifier directly on the available predictors. Bold values indicate the highest prediction accuracy for each dataset."
)
  ) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8
  )


## ----svmodt-feature-selection-table-html, eval=knitr::is_html_output()--------
# tbl_feature_bold |>
#   kbl(
#     row.names = FALSE,
#     col.names = c(
#       "Dataset", "N", "X", "L",
#       "STree (Benchmark)", "Random", "Mutual Info", "Correlation"
#     ),
#     align = "lcccccccc",
#     escape = FALSE,
#     caption = paste0(
#   "Comparison of mean prediction accuracy across feature selection strategies for SVMODT, benchmarked against the Python STree implementation. All SVMODT models were trained using \\(d_{\\max}=15\\). The random strategy selects candidate predictors using random subset sampling \\(n_{\\text{subsets}}=10\\); the mutual information strategy ranks predictors according to their dependency with the response variable; the correlation strategy ranks predictors using absolute correlation with the response. STree does not employ an explicit pre-split feature ranking mechanism, instead optimising the node classifier directly on the available predictors. Bold values indicate the highest prediction accuracy for each dataset."
# )
#   ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )
# 


## ----wine-feature-penalty, fig.align='center', results='asis', fig.cap="Comparison of Low, Medium and High penalty on repeated features by SVMODT on Wine dataset.", fig.subcap=c('No Penalty', 'Low (0.2)', 'Medium (0.5)', 'High (0.8)'), out.width = '30%', fig.pos='h'----
wine <- read.table("data/wine_R.dat") |>
  mutate(clase = as.factor(clase)) |> svmodt:::standard_scaler()

fit_no_penalty <- svm_split(
  data = wine,
  response = "clase",
  max_depth = 8,
  min_samples = 5,
  max_features = 4,
  feature_method = "mutual", 
  penalize_used_features = FALSE
)

fit_low_penalty <- svm_split(
  data = wine,
  response = "clase",
  max_depth = 8,
  min_samples = 5,
  max_features = 4,
  feature_method = "mutual",
  penalize_used_features = TRUE, 
  feature_penalty_weight = 0.2
)

fit_medium_penalty <- svm_split(
  data = wine,
  response = "clase",
  max_depth = 8,
  min_samples = 5,
  max_features = 4,
  feature_method = "mutual",
  penalize_used_features = TRUE,
  feature_penalty_weight = 0.5
)

fit_high_penalty <- svm_split(
  data = wine,
  response = "clase",
  max_depth = 8,
  min_samples = 5,
  max_features = 4,
  feature_method = "mutual",
  penalize_used_features = TRUE,
  feature_penalty_weight = 0.8
)

source("analysis/feature-usage.R")

no_pen_feature_usage <- summarise_feature_usage(tree = fit_no_penalty)
low_pen_feature_usage <- summarise_feature_usage(tree = fit_low_penalty)
medium_pen_feature_usage <- summarise_feature_usage(tree = fit_medium_penalty)
high_pen_feature_usage <- summarise_feature_usage(tree = fit_high_penalty)

#Side-by-side comparison plot
plot_penalty_comparison <- function(tree_none, tree_penalised,
                                    label_none = "No Penalty",
                                    label_pen  = "Penalised") {
  
  usage_none <- summarise_feature_usage(tree_none) |>
    mutate(model = label_none)
  
  usage_pen  <- summarise_feature_usage(tree_penalised) |>
    mutate(model = label_pen)
  
  bind_rows(usage_none, usage_pen) |>
    mutate(model = factor(model, levels = c(label_none, label_pen))) |>
    ggplot(aes(x = reorder(feature, count), y = count, fill = model)) +
    geom_col(position = "dodge", width = 0.7) +
    geom_text(aes(label = count),
              position = position_dodge(width = 0.7),
              hjust = -0.3, size = 3) +
    coord_flip() +
    scale_fill_manual(values = c("#4E79A7", "#F28E2B")) +
    labs(
      #title    = "Feature Usage: Penalised vs No Penalty",
      #subtitle = "Lower reuse of repeated features indicates effective penalisation",
      x        = "Feature",
      y        = "Node Count",
      fill     = NULL
    ) +
    theme_minimal() +
    theme(
      plot.title    = element_text(face = "bold"),
      legend.position = "top",
      axis.text.y   = element_text(size = 9)
    )
}

plot_penalty_comparison(tree_none = fit_no_penalty, tree_penalised = fit_low_penalty, label_pen = "Low Penalty")
plot_penalty_comparison(tree_none = fit_no_penalty, tree_penalised = fit_medium_penalty,  label_pen = "Medium Penalty")
plot_penalty_comparison(tree_none = fit_no_penalty, tree_penalised = fit_high_penalty, label_pen =  "High Penalty")



## ----svmodt-features-penalty-score-table-setup--------------------------------
svmodt_penalty_none   <- readRDS("analysis/results/svmodt_penalty_none.rds")
svmodt_penalty_low    <- readRDS("analysis/results/svmodt_penalty_low.rds")
svmodt_penalty_medium <- readRDS("analysis/results/svmodt_penalty_medium.rds")
svmodt_penalty_high   <- readRDS("analysis/results/svmodt_penalty_high.rds")
py_stree              <- readRDS("analysis/results/py_stree.rds")


svmodt_penalty_none <- svmodt_penalty_none[,1:9]
svmodt_penalty_low <- svmodt_penalty_low[,1:9]
svmodt_penalty_medium <- svmodt_penalty_medium[,1:9]
svmodt_penalty_high <- svmodt_penalty_high[,1:9]


tbl_penalty <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  apply(as.matrix(svmodt_penalty_none),   2, mean_sd),
  apply(as.matrix(svmodt_penalty_low),    2, mean_sd),
  apply(as.matrix(svmodt_penalty_medium), 2, mean_sd),
  apply(as.matrix(svmodt_penalty_high),   2, mean_sd),
  stringsAsFactors = FALSE
)

model_cols_penalty <- 5:8

tbl_penalty_bold <- tbl_penalty
tbl_penalty_bold[model_cols_penalty] <- t(apply(tbl_penalty[model_cols_penalty], 1, function(row) {
  means   <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))


## ----svmodt-features-penalty-score-table-latex, eval=knitr::is_latex_output(), fig.pos='h'----
tbl_penalty_bold |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L", "None (Benchmark)", "Low", "Medium", "High"
    ),
    align  = "lccccccc",
    escape = FALSE,
    caption = paste0(
      "Comparison of mean prediction accuracy (mean \\(\\pm\\) standard deviation) across feature penalisation strategies for SVMODT. All models were trained using \\(d_{\\max}=15\\), mutual-information feature ranking, and adaptive maximum feature selection. No penalisation corresponds to reuse of previously selected features being unrestricted. Low, medium, and high penalisation correspond to feature penalty weights of \\(\\lambda\\) = 0.2, \\(\\lambda\\) = 0.5, and \\(\\lambda\\) = 0.8, respectively. Bold values indicate the highest accuracy for each dataset."
    )
  ) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 8
  )


## ----svmodt-features-penalty-score-table-html, eval=knitr::is_html_output()----
# tbl_penalty_bold |>
#   kbl(
#     row.names = FALSE,
#     col.names = c(
#       "Dataset", "N", "X", "L", "None (Benchmark)", "Low", "Medium", "High"
#     ),
#     align  = "lccccccc",
#     escape = FALSE,
#     caption = paste0(
#       "Comparison of mean prediction accuracy (mean \\(\\pm\\) standard deviation) across feature penalisation strategies for SVMODT. All models were trained using \\(d_{\\max}=15\\), mutual-information feature ranking, and adaptive maximum feature selection. No penalisation corresponds to reuse of previously selected features being unrestricted. Low, medium, and high penalisation correspond to feature penalty weights of \\(\\lambda\\) = 0.2, \\(\\lambda\\) = 0.5, and \\(\\lambda\\) = 0.8, respectively. Bold values indicate the highest accuracy for each dataset."
#     )
#   ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----min-split-table-setup----------------------------------------------------
count_tree_nodes <- function(tree) {
  
  splits <- function(node) {
    if (is.null(node) || isTRUE(node$is_leaf)) return(0L)
    1L + splits(node$left) + splits(node$right)
  }
  
  leaves <- function(node) {
    if (is.null(node)) return(0L)
    if (isTRUE(node$is_leaf)) return(1L)
    leaves(node$left) + leaves(node$right)
  }
  
  c(
    splits = splits(tree),
    leaves = leaves(tree),
    total_nodes = splits(tree) + leaves(tree)
  )
}

set.seed(17)
wdbc_split <- initial_split(data = wdbc, prop = 0.8, strata =  diagnosis)
wdbc_train <- training(wdbc_split)
wdbc_test <- testing(wdbc_split)

tree_wdbc_min_10_sample <- svm_split(data = wdbc_train, response = "diagnosis", min_samples = 10, feature_method = "mutual", max_features_strategy = "random")
tree_wdbc_min_50_sample <- svm_split(data = wdbc_train, response = "diagnosis", min_samples = 50, feature_method = "mutual", max_features_strategy = "random")


acc_wdbc_10_sample <- mean(svm_predict_tree(tree = tree_wdbc_min_10_sample, newdata = wdbc_test) == wdbc_test$diagnosis)
acc_wdbc_50_sample <- mean(svm_predict_tree(tree = tree_wdbc_min_50_sample, newdata = wdbc_test) == wdbc_test$diagnosis)

min_sample_table <- cbind(rbind(`10` = count_tree_nodes(tree_wdbc_min_10_sample), 
            `50` = count_tree_nodes(tree_wdbc_min_50_sample)), 
      round(rbind(acc_wdbc_10_sample, 
                  acc_wdbc_50_sample), 4)) 


## ----min-split-table-latex, eval=knitr::is_latex_output(),fig.pos='h'---------
min_sample_table |>
  as.data.frame() |>
  tibble::rownames_to_column(var = "Min Samples") |>
  kable(col.names = c("Min Samples", "Splits", "Leaves", "Total Nodes", "Accuracy"),
        align = "lcccc",
        row.names = FALSE,
        caption = "Comparison of tree structure and predictive accuracy across minimum sample thresholds on the WDBC dataset. All SVMODT models were trained using the random maximum feature strategy and mutual information feature ranking. Higher minimum sample thresholds restrict further node splitting and therefore produce shallower tree structures.") |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8
  )


## ----min-split-table-html, eval=knitr::is_html_output()-----------------------
# min_sample_table |>
#   as.data.frame() |>
#   tibble::rownames_to_column(var = "Min Samples") |>
#   kable(col.names = c("Min Samples", "Splits", "Leaves", "Total Nodes", "Accuracy"),
#         align = "ccccc",
#         escape = FALSE,
#         caption = "Comparison of tree structure and predictive accuracy across minimum sample thresholds on the WDBC dataset. All SVMODT models were trained using the random maximum feature strategy and mutual information feature ranking. Higher minimum sample thresholds restrict further node splitting and therefore produce shallower tree structures.") |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----max-depth-table-setup----------------------------------------------------
cardiotocography <- read.table("data/cardiotocography-3clases_R.dat") |>
  mutate(clase = as.factor(clase)) |> svmodt:::standard_scaler()

set.seed(17)
cardio_split <- initial_split(data = cardiotocography, prop = 0.8, strata = clase)
cardio_train <- training(cardio_split)
cardio_test <- testing(cardio_split)

tree_cardio_depth_3 <- svm_split(data = cardio_train, response = "clase", max_depth = 3)
tree_cardio_depth_5 <- svm_split(data = cardio_train, response = "clase", max_depth = 5)
tree_cardio_depth_7 <- svm_split(data = cardio_train, response = "clase", max_depth = 7)

acc_cardio_depth_2 <- mean(svm_predict_tree(tree = tree_cardio_depth_3, newdata = cardio_test) == cardio_test$clase)
acc_cardio_depth_5 <- mean(svm_predict_tree(tree = tree_cardio_depth_5, newdata = cardio_test) == cardio_test$clase)
acc_cardio_depth_7 <- mean(svm_predict_tree(tree = tree_cardio_depth_7, newdata = cardio_test) == cardio_test$clase)



## ----max-depth-table-latex, eval=knitr::is_latex_output(), fig.pos='h'--------
cbind(rbind(`3` = count_tree_nodes(tree_cardio_depth_3), 
            `5` = count_tree_nodes(tree_cardio_depth_5), 
            `7` = count_tree_nodes(tree_cardio_depth_7)),
      round(rbind(acc_cardio_depth_2, acc_cardio_depth_5, acc_cardio_depth_7),4)) |>
  as.data.frame() |>
  tibble::rownames_to_column(var = "Max Depth") |>
  kable(col.names = c("Max Depth", "Splits", "Leaves", "Total Nodes", "Accuracy"),
        align = "lcccc",
        caption = paste0(
  "Comparison of tree structure and accuracy across different maximum tree depths on the Cardiotocography dataset.")) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8)


## ----max-depth-table-html, eval=knitr::is_html_output()-----------------------
# cbind(rbind(`3` = count_tree_nodes(tree_cardio_depth_3),
#             `5` = count_tree_nodes(tree_cardio_depth_5),
#             `7` = count_tree_nodes(tree_cardio_depth_7)),
#       round(rbind(acc_cardio_depth_2, acc_cardio_depth_5, acc_cardio_depth_7),4)) |>
#   as.data.frame() |>
#   tibble::rownames_to_column(var = "Max Depth") |>
#   kable(col.names = c("Max Depth", "Splits", "Leaves", "Total Nodes", "Accuracy"),
#         align = "lcccc",
#         escape = FALSE,
#         caption = paste0(
#   "Comparison of tree structure and accuracy across different maximum tree depths on the Cardiotocography dataset.")) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----min-impurity-table-setup-------------------------------------------------
cardiotocography <- read.table("data/cardiotocography-3clases_R.dat") |>
  mutate(clase = as.factor(clase)) |> svmodt:::standard_scaler()

set.seed(17)
cardio_split <- initial_split(data = cardiotocography, prop = 0.8, strata = clase)
cardio_train <- training(cardio_split)
cardio_test <- testing(cardio_split)

tree_cardio_impurity_0005 <- svm_split(data = cardio_train, response = "clase", max_depth = 5, min_impurity_decrease = 0.005)

tree_cardio_impurity_001 <- svm_split(data = cardio_train, response = "clase", max_depth = 5, min_impurity_decrease = 0.01)

tree_cardio_impurity_01 <- svm_split(data = cardio_train, response = "clase", max_depth = 5, min_impurity_decrease = 0.1)


acc_cardio_impurity_0005 <- mean(svm_predict_tree(tree = tree_cardio_impurity_0005, newdata = cardio_test) == cardio_test$clase)
acc_cardio_impurity_001 <- mean(svm_predict_tree(tree = tree_cardio_impurity_001, newdata = cardio_test) == cardio_test$clase)
acc_cardio_impurity_01 <- mean(svm_predict_tree(tree = tree_cardio_impurity_01, newdata = cardio_test) == cardio_test$clase)


## ----min-impurity-table-latex, eval=knitr::is_latex_output(),fig.pos='h'------
cbind(rbind(`0.005` = count_tree_nodes(tree_cardio_impurity_0005), 
            `0.01` = count_tree_nodes(tree_cardio_impurity_001), 
            `0.1` = count_tree_nodes(tree_cardio_impurity_01)),
      round(rbind(acc_cardio_impurity_0005, acc_cardio_impurity_001, acc_cardio_impurity_01),4)) |>
  as.data.frame() |>
  tibble::rownames_to_column(var = "Impurity Threshold") |>
  kable(col.names = c("Impurity Threshold", "Splits", "Leaves", "Total Nodes", "Accuracy"),
        align = "lcccc",
        escape = FALSE,
        caption = paste0(
  "Comparison of tree structure and accuracy across different minimum impurity threshold values on the Cardiotocography dataset.")) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 8)


## ----min-impurity-table-html, eval=knitr::is_html_output()--------------------
# cbind(rbind(`0.005` = count_tree_nodes(tree_cardio_impurity_0005),
#             `0.01` = count_tree_nodes(tree_cardio_impurity_001),
#             `0.1` = count_tree_nodes(tree_cardio_impurity_01)),
#       round(rbind(acc_cardio_impurity_0005, acc_cardio_impurity_001, acc_cardio_impurity_01),4)) |>
#   as.data.frame() |>
#   tibble::rownames_to_column(var = "Impurity Threshold") |>
#   kable(col.names = c("Impurity Threshold", "Splits", "Leaves", "Total Nodes", "Accuracy"),
#         align = "lcccc",
#         escape = FALSE,
#         caption = paste0(
#   "Comparison of tree structure and accuracy across different minimum impurity threshold values on the Cardiotocography dataset.")) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----palmer-penguins-weighted-split-latex, eval=knitr::is_latex_output(), fig.align='center', results='asis', fig.cap="Comparison of equal, balanced, and custom weighting schemes using SVMODT on the Palmer Penguins dataset.", fig.subcap=c('equal', 'balanced', 'custom'), fig.width = 6----
fit_none <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features = 3, class_weights = "none"
)

fit_balanced <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features = 3, class_weights = "balanced"
)

custom_weights <- c("Adelie" = 2, "Gentoo" = 1, "Chinstrap" = 5)

fit_custom <- svm_split(
  data = penguins_orsf,
  response = "species",
  max_depth = 4,
  min_samples = 5,
  feature_method = "mutual",
  max_features = 3, class_weights = "custom", custom_class_weights = custom_weights
)

plot1 <- plot_svmodt_surface(fit_none, penguins_orsf, "species")
plot2 <- plot_svmodt_surface(fit_balanced, penguins_orsf, "species")
plot3 <- plot_svmodt_surface(fit_custom, penguins_orsf, "species")

ggarrange(plot1, plot2, plot3, nrow = 1, common.legend = TRUE, legend = "right")


## ----palmer-penguins-weighted-split-html, eval=knitr::is_html_output(), fig.align='center', results='asis', fig.cap="Comparison of Equal, Balanced and Custom Weights by SVMODT on Palmerpenguins dataset. WHATS THE DIFFERENCE BETWEEN STREE AND NONE", fig.subcap=c('equal', 'balanced', 'custom'), out.width = '30%'----
# knitr::include_graphics(path = "analysis/results/class-weights/none/tour-none.gif")
# knitr::include_graphics(path = "analysis/results/class-weights/balanced/tour-balanced.gif")
# knitr::include_graphics(path = "analysis/results/class-weights/custom/tour-balanced-sub.gif")


## ----svmodt-class-weight-f1-score-table---------------------------------------
# Load F1 results
svmodt_weights_none_f1 <- readRDS("analysis/results/svmodt_weights_none_f1.rds")
svmodt_weights_balanced_f1 <- readRDS("analysis/results/svmodt_weights_balanced_f1.rds")
py_stree <- readRDS("analysis/results/py_stree_f1.rds")
class_imbalance_ratio <- readRDS("analysis/results/class-imbalance-ratio.RDS")

svmodt_weights_none_f1 <- svmodt_weights_none_f1[,1:9]
svmodt_weights_balanced_f1 <- svmodt_weights_balanced_f1[,1:9]
py_stree <- py_stree[,1:9]
class_imbalance_ratio <- class_imbalance_ratio[1:9]

tbl_weights_f1 <- data.frame(
  data_names,
  data_num_observations,
  data_num_features,
  data_num_classes,
  class_imbalance_ratio,
  apply(as.matrix(py_stree), 2, mean_sd),
  apply(as.matrix(svmodt_weights_none_f1), 2, mean_sd),
  apply(as.matrix(svmodt_weights_balanced_f1), 2, mean_sd),
  stringsAsFactors = FALSE
)

model_cols_f1 <- 6:8

tbl_weights_f1_bold <- tbl_weights_f1
tbl_weights_f1_bold[model_cols_f1] <- t(apply(tbl_weights_f1[model_cols_f1], 1, function(row) {
  means <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))



## ----svmodt-class-weight-f1-score-table-latex, eval=knitr::is_latex_output()----
tbl_weights_f1_bold |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L", "Class Imbalance Ratio",
      "STree", "None", "Balanced"
    ),
    align = "lccccccc",
    escape = FALSE,
    caption = paste0(
  "Comparison of macro-averaged F1 score (mean \\(\\pm\\) sd) across class weighting strategies. All SVMODT models are trained with \\(d_{\\max}=15\\), \\(\\mathrm{strat}_{m}=\\texttt{\"mutual\"}\\). None: \\(\\mathrm{strat}_{w}=\\texttt{\"none\"}\\); Balanced: \\(\\mathrm{strat}_{w}=\\texttt{\"balanced\"}\\). Bold values denote the highest F1 score for each dataset."
)
  ) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 8
  )


## ----svmodt-class-weight-f1-score-table-html, eval=knitr::is_html_output()----
# tbl_weights_f1_bold |>
#   kbl(
#     row.names = FALSE,
#     col.names = c(
#       "Dataset", "N", "X", "L", "Class Imbalance Ratio",
#       "STree", "None", "Balanced"
#     ),
#     align = "lccccccc",
#     escape = FALSE,
#     caption = paste0(
#   "Comparison of macro-averaged F1 score (mean \\(\\pm\\) sd) across class weighting strategies. All SVMODT models are trained with \\(d_{\\max}=15\\), \\(\\mathrm{strat}_{m}=\\texttt{\"mutual\"}\\). None: \\(\\mathrm{strat}_{w}=\\texttt{\"none\"}\\); Balanced: \\(\\mathrm{strat}_{w}=\\texttt{\"balanced\"}\\). Bold values denote the highest F1 score for each dataset."
# )
#   ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----tbl-benchmark-model-setup------------------------------------------------
benchmark_summary_table <- readRDS("analysis/results/benchmark_summary_table.rds")
benchmark_summary_table <- benchmark_summary_table[,-6:-7]  
models <- 5:12

bold_benchmark_summary_table <- benchmark_summary_table
bold_benchmark_summary_table[models] <- t(apply(benchmark_summary_table[models], 1, function(row) {
  means   <- as.numeric(sub(" \u00B1.*", "", row))
  max_idx <- which(means == max(means, na.rm = TRUE))
  out <- row
  out[max_idx] <- cell_spec(out[max_idx], bold = TRUE)
  out
}))

table_a <- bold_benchmark_summary_table[, c(1:4, 5:8)]
table_b <- bold_benchmark_summary_table[, c(1:4, 9:12)]


## ----tbl-benchmark-model-latex-a, eval=knitr::is_latex_output()---------------
table_a |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L",
      "CART*",
      "SVM (linear)",
      "AORSF",
      "Log. Reg."
    ),
    align  = paste0("l", paste(rep("c", ncol(table_a) - 1), collapse = "")),
    escape = FALSE,
    caption = paste0(
      "Comparison of Mean Prediction Accuracy (mean \\(\\pm\\) sd) across classifiers (Part 1). ",
      "Bold denotes the highest accuracy per dataset."
    )
  ) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 6
  )


## ----tbl-benchmark-model-latex-b, eval=knitr::is_latex_output()---------------
table_b |>
  kable(
    row.names = FALSE,
    col.names = c(
      "Dataset", "N", "X", "L",
      "PPTree",
      "STree*",
      "SVMODT (Default)",
      "SVMODT*"
    ),
    align  = paste0("l", paste(rep("c", ncol(table_b) - 1), collapse = "")),
    escape = FALSE,
    caption = paste0(
      "Comparison of Mean Prediction Accuracy (mean \\(\\pm\\) sd) across classifiers (Part 2). ",
      "\\textit{STree*} denotes Python STree with dataset-specific hyperparameters. ",
      "\\textit{SVMODT*} denotes SVMODT with tuned hyperparameters from grid search. ",
      "Bold denotes the highest accuracy per dataset."
    )
  ) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 6
  )


## ----tbl-benchmark-model-html, eval= knitr::is_html_output()------------------
# bold_benchmark_summary_table |>
#   kbl(
#     row.names = FALSE,
#     col.names = c(
#       "Dataset", "N", "X", "L",
#       "CART*",
#       "SVM (linear)",
#       "AORSF",
#       "Log. Reg.",
#       "PPTree",
#       "STree*",
#       "SVMODT (Default)",
#       "SVMODT*"
#     ),
#     align  = paste0("l", paste(rep("c", ncol(bold_benchmark_summary_table) - 1), collapse = "")),
#     escape = FALSE,
#     caption = paste0(
#       "Comparison of Mean Prediction Accuracy (mean \\(\\pm\\) sd) across classifiers. ",
#       "\\textit{STree*} denotes Python STree with dataset-specific hyperparameters. ",
#       "\\textit{SVMODT*} denotes SVMODT with tuned hyperparameters from grid search. ",
#       "Bold denotes the highest accuracy per dataset."
#     )
#   ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )


## ----table-best-param-grid-setup----------------------------------------------
best_param <- readRDS(file = "analysis/results/grid_search_best_params.rds")

best_param <- best_param[1:9,1:8]


## ----table-best-param-grid-latex, eval=knitr::is_latex_output(), fig.pos='h'----
best_param |> kable(
  caption = "Hyperparameters Selected through the Grid Search Procedure.",
  col.names = c("Dataset", "Max Depth", "Feature Selection Method", "Class Weight Strategy", "Max Feature Strategy", "Penalize Used Features", "Feature Penalty Weight", "Impurity Decrease") 
) |>
  kable_styling(
    full_width = FALSE,
    position   = "center",
    font_size  = 4,
    latex_options = "hold_position"
  )

## ----table-best-param-grid-html, eval=knitr::is_html_output()-----------------
# best_param |> kbl(
#   caption = "Hyperparameters Selected through the Grid Search Procedure.",
#   col.names = c("Dataset", "Max Depth", "Feature Selection Method", "Class Weight Strategy", "Max Feature Strategy", "Penalize Used Features", "Feature Penalty Weight", "Impurity Decrease"),
#   escape = FALSE
# ) |>
#   kable_styling(
#     bootstrap_options = c("striped", "hover", "condensed"),
#     full_width = FALSE,
#     position = "center",
#     font_size = 8
#   )

